// <copyright file="ClientStackTest.PUT_ToBinaryStackTest.g.cs">Copyright ? 2018</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DataStructures.Test
{
    public partial class ClientStackTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest198()
{
    string s;
    s = this.PUT_ToBinaryStackTest(0);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest796()
{
    string s;
    s = this.PUT_ToBinaryStackTest(1);
    Assert.AreEqual<string>("1", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest948()
{
    string s;
    s = this.PUT_ToBinaryStackTest(2);
    Assert.AreEqual<string>("10", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest517()
{
    string s;
    s = this.PUT_ToBinaryStackTest(5);
    Assert.AreEqual<string>("101", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest31()
{
    string s;
    s = this.PUT_ToBinaryStackTest(21);
    Assert.AreEqual<string>("10101", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ClientStackTest))]
public void PUT_ToBinaryStackTest909()
{
    string s;
    s = this.PUT_ToBinaryStackTest(340);
    Assert.AreEqual<string>("101010100", s);
}
    }
}
